// S3LAB
// Header for shared constants between pass and compiler-rt
//
// vim: ts=2:sw=2:expandtab
#ifndef DECOUPLE_H
#define DECOUPLE_H

//#define CHECK_SMALL_REGION_THRESHOLD


typedef enum {
	CHECK_SMALL_REGION,
	CHECK_SMALL_REGION_EXP,
	CHECK_LARGE_REGION,
	CHECK_LARGE_REGION_EXP,
	CHECK_ODR,
	CHECK_REGION_COPY,
	CHECK_ACCESS_1,
	CHECK_ACCESS_2,
	CHECK_ACCESS_4,
	CHECK_ACCESS_8,
	CHECK_ACCESS_16,
	CHECK_ACCESS_EXP_1,
	CHECK_ACCESS_EXP_2,
	CHECK_ACCESS_EXP_4,
	CHECK_ACCESS_EXP_8,
	CHECK_ACCESS_EXP_16,
	CHECK_CXX_ARRAY_COOKIE,
	ALLOCATE_LONG,
	ALLOCATE_SHORT,
	USER_POISON_WITH_VALUE,
	POISON_WITH_VALUE,
	POISON_PRR,
	POISON_ALIGNED_STACK_MEM,
	POISON_INTRA_OBJ_REDZONE,
	SANITIZER_ANNOTATE_CONTIGUOUS,
	FLUSH_UNNEEDED,
	CHECK_FOR_INVALID_PAIR,
	POISON_STACK_ENTRY,
	POISON_STACK_ENTRY_BYTES,
	OPCODE_MAX
} opcode_t;

#endif  // DECOUPLE_H
